name: grund210219
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pysimplegui
  - conda-env
  - conda-build
  - conda-verify
  - _ipyw_jlab_nb_ext_conf
  - anaconda
  - anaconda-navigator
  - navigator-updater
  - jupyterlab_widgets
  - ipywidgets
  - mayavi
  - ipyevents
  - ipympl
  - sympy
